variabilize repo
Change-Id: I9faccb8e8168ee914d688208dc7e503a310811a1

diff --git a/.github/workflows/analyzer.yml b/.github/workflows/analyzer.yml
--- a/.github/workflows/analyzer.yml
+++ b/.github/workflows/analyzer.yml
@@ -40,9 +40,6 @@ on:
   schedule:
     - cron: '0 6 * * *'    # Runs at 06:00 UTC
 
-#env:
-#  FILE: './iptv/telegram/iptv.txt'
-
 concurrency:
   group: analyzer-queue
   cancel-in-progress: false
@@ -55,19 +52,6 @@ jobs:
     steps:
       - name: Checkout GitHub Repo
         uses: actions/checkout@v4
-      - name: Restore telegram scripts
-        if: ${{ false }}
-        run: |
-          gpg --decrypt --batch --passphrase "${{ secrets.PGP_PWD }}" -o ./iptv/telegram/my_session.session ./iptv/telegram/my_session.session_enc
-          
-          [[ -f ${{ env.FILE }} ]] && rm ${{ env.FILE }}
-          pip install telethon
-          declare -a tge=("ariptvstalker" "StbEmucodesStalkerPortal" "+7eels9HzyOA4ZTBl")
-           for tg in "${tge[@]}";
-           do
-            echo "Read content of t.me/$tg"
-            python ./iptv/telegram/telegram-iptv-script.py t.me/$tg >> ${{ env.FILE }}
-           done
       - name: Download dropbox files
         uses: gomes042/gh-actions-dropbox/files/download_zip@60f2d1f429591142b2ed6c2a22fe620b611de460
         with:
@@ -82,26 +66,26 @@ jobs:
           ls -lrth dropbox/files
       - name: Clone repo and restore files
         run: |
-          git clone https://x-access-token:${{ secrets.STALKER_REPO_PAT }}@github.com/Macadoshis/stalker-to-m3u.git
+          git clone https://x-access-token:${{ secrets.STALKER_REPO_PAT }}@github.com/${{ secrets.SOURCE_REPO }} repo
           
-          cp dropbox/files/succeeded.json stalker-to-m3u/tools/
-          cp dropbox/files/failed.json stalker-to-m3u/tools/
-          cp dropbox/files/sources.txt stalker-to-m3u/tools/
-          cp dropbox/files/iptv.txt stalker-to-m3u/
+          cp dropbox/files/succeeded.json repo/tools/
+          cp dropbox/files/failed.json repo/tools/
+          cp dropbox/files/sources.txt repo/tools/
+          cp dropbox/files/iptv.txt repo/
           cp dropbox/files/links.txt ./
       - name: Update summary
         run: |
           echo "## CURRENT content" >> $GITHUB_STEP_SUMMARY
           echo -e "| succeeded.json | failed.json    |" >> $GITHUB_STEP_SUMMARY
           echo -e "|----------------|----------------|" >> $GITHUB_STEP_SUMMARY
-          echo -e "| `jq 'length' ./stalker-to-m3u/tools/succeeded.json || echo 0`   | `jq 'length' ./stalker-to-m3u/tools/failed.json || echo 0`   |" >> $GITHUB_STEP_SUMMARY
+          echo -e "| `jq 'length' ./repo/tools/succeeded.json || echo 0`   | `jq 'length' ./repo/tools/failed.json || echo 0`   |" >> $GITHUB_STEP_SUMMARY
       - name: Configure NODE
         uses: actions/setup-node@v4
         with:
           node-version: ${{ vars.NODE_VERSION }}
-      - name: Prepare stalker environment
+      - name: Prepare environment
         run: |
-          cd stalker-to-m3u
+          cd repo
           node -v
           npm -v
           npm config set loglevel info
@@ -122,21 +106,21 @@ jobs:
           # free -h
       - name: Run analyzer
         run: |
-          cd stalker-to-m3u
+          cd repo
           tools/./iptv-analyzer --cache="true" --groupsToTest=${{ inputs.groupsToTest || 3 }} --channelsToTest=${{ inputs.channelsToTest || 3 }} --retestSuccess=${{ inputs.retestSuccess || false }} --retestFailed=${{ inputs.retestFailed || false }} --streamTester=${{ inputs.streamTester || 'ffmpeg' }} --threadsCount=${{ inputs.threadsCount || 15 }} > /dev/null 2>&1
       - name: Update summary
         run: |
           echo "## RESULT content" >> $GITHUB_STEP_SUMMARY
           echo -e "| succeeded.json | failed.json    |" >> $GITHUB_STEP_SUMMARY
           echo -e "|----------------|----------------|" >> $GITHUB_STEP_SUMMARY
-          echo -e "| `jq 'length' ./stalker-to-m3u/tools/succeeded.json || echo 0`   | `jq 'length' ./stalker-to-m3u/tools/failed.json || echo 0`   |" >> $GITHUB_STEP_SUMMARY
+          echo -e "| `jq 'length' ./repo/tools/succeeded.json || echo 0`   | `jq 'length' ./repo/tools/failed.json || echo 0`   |" >> $GITHUB_STEP_SUMMARY
       - name: Save succeeded.json to dropbox
         uses: gomes042/gh-actions-dropbox/files/upload@60f2d1f429591142b2ed6c2a22fe620b611de460
         with:
           DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
           DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
           DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
-          SOURCE_PATH: ./stalker-to-m3u/tools/succeeded.json
+          SOURCE_PATH: ./repo/tools/succeeded.json
           DEST_PATH: /files/succeeded.json
       - name: Save failed.json to dropbox
         uses: gomes042/gh-actions-dropbox/files/upload@60f2d1f429591142b2ed6c2a22fe620b611de460
@@ -144,7 +128,7 @@ jobs:
           DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
           DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
           DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
-          SOURCE_PATH: ./stalker-to-m3u/tools/failed.json
+          SOURCE_PATH: ./repo/tools/failed.json
           DEST_PATH: /files/failed.json
       - name: Verify links
         run: |
