Add generator.yml

diff --git a/.github/workflows/analyzer.yml b/.github/workflows/analyzer.yml
--- a/.github/workflows/analyzer.yml
+++ b/.github/workflows/analyzer.yml
@@ -52,7 +52,7 @@ jobs:
       - name: Clone repo and restore files
         run: |
           git clone https://github.com/Macadoshis/stalker-to-m3u.git
-          git clone https://gist.github.com/${{ secrets.GIST }}.git gist
+          git clone https://x-access-token:${{ secrets.GIST_TOKEN }}@gist.github.com/${{ secrets.GIST }}.git gist
           
           cp gist/succeeded.json stalker-to-m3u/tools/succeeded.json
           cp gist/failed.json stalker-to-m3u/tools/failed.json
@@ -62,7 +62,7 @@ jobs:
       - name: Update summary
         run: |
           echo "## CURRENT content" >> $GITHUB_STEP_SUMMARY
-          echo -e "| succeeded.json | succeeded.json |" >> $GITHUB_STEP_SUMMARY
+          echo -e "| succeeded.json | failed.json    |" >> $GITHUB_STEP_SUMMARY
           echo -e "|----------------|----------------|" >> $GITHUB_STEP_SUMMARY
           echo -e "| `jq 'length' ./stalker-to-m3u/tools/succeeded.json || echo 0`   | `jq 'length' ./stalker-to-m3u/tools/failed.json || echo 0`   |" >> $GITHUB_STEP_SUMMARY
       - name: Configure NODE
@@ -92,18 +92,20 @@ jobs:
       - name: Run analyzer
         run: |
           cd stalker-to-m3u
-          tools/./iptv-analyzer --cache="true" --groupsToTest=${{ inputs.groupsToTest || 5 }} --channelsToTest=${{ inputs.channelsToTest || 5 }} --retestSuccess=$${{ inputs.retestSuccess || false }} --streamTester=${{ inputs.streamTester || 'ffmpeg' }}
+          tools/./iptv-analyzer --cache="true" --groupsToTest=${{ inputs.groupsToTest || 5 }} --channelsToTest=${{ inputs.channelsToTest || 5 }} --retestSuccess=$${{ inputs.retestSuccess || false }} --streamTester=${{ inputs.streamTester || 'ffmpeg' }} --threadsCount=5 > /dev/null 2>&1
       - name: Update summary
         run: |
           echo "## RESULT content" >> $GITHUB_STEP_SUMMARY
-          echo -e "| succeeded.json | succeeded.json |" >> $GITHUB_STEP_SUMMARY
+          echo -e "| succeeded.json | failed.json    |" >> $GITHUB_STEP_SUMMARY
           echo -e "|----------------|----------------|" >> $GITHUB_STEP_SUMMARY
           echo -e "| `jq 'length' ./stalker-to-m3u/tools/succeeded.json || echo 0`   | `jq 'length' ./stalker-to-m3u/tools/failed.json || echo 0`   |" >> $GITHUB_STEP_SUMMARY
       - name: Save succeeded.json
         run: |
           cd gist
+          git config user.name "github-actions[bot]"
+          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
           cp -ap ../stalker-to-m3u/tools/succeeded.json ./
           cp -ap ../stalker-to-m3u/tools/failed.json ./
           git add succeeded.json failed.json
           git commit -m "Update content (CI)"
-          git push
+          git push || echo "Nothing to push"
